version: 0.1
env:
  secrets-manager:
    TOKEN: SecretNameSonar:TokenForSonar
phases:
  build:
    commands:
      - |
        mvn verify sonar:sonar \
        -Dsonar.projectKey=javaprojectawsayush \
        -Dsonar.organization=javaprojectawsayush \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=$TOKEN
